version: '3.8'

services:


  backend:
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    volumes:
      - .:/workspace
    networks:
      - app-network
    ports:
      - "8000:8000"
    env_file:
      - .env
    # depends_on:
    #   db:
    #     condition: service_healthy

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: app/frontend/Dockerfile
  #   volumes:
  #     - .:/workspace:consistent
  #   networks:
  #     - app-network
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - backend

# volumes:
#   db_data:

networks:
  app-network:
    driver: bridge