services:
  db:
    image: mysql:8.4.6
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --port=3307 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./.docker/db/data:/var/lib/mysql
    - ./.docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./.docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3307:3307
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: .devcontainer/backend/Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /workspace
    working_dir: /workspace
    networks:
      - app-network
    env_file:
      - .env
    command: ["tail", "-f", "/dev/null"]

  frontend:
    build:
      context: .
      dockerfile: .devcontainer/frontend/Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /workspace
    working_dir: /workspace
    networks:
      - app-network
    depends_on:
      - backend
    command: ["tail", "-f", "/dev/null"]

networks:
  app-network:
    driver: bridge
