// <auto-generated />
using HouseholdBudget.Infrastructure.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HouseholdBudget.Infrastructure.EFCore.EFEntities.CsvImports", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_csv_imports");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_csv_imports_user_id");

                    b.ToTable("csv_imports", (string)null);
                });

            modelBuilder.Entity("HouseholdBudget.Infrastructure.EFCore.EFEntities.RecurringTransactions", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_recurring_transactions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_recurring_transactions_user_id");

                    b.ToTable("recurring_transactions", (string)null);
                });

            modelBuilder.Entity("HouseholdBudget.Infrastructure.EFCore.EFEntities.Transactions", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category");

                    b.Property<string>("CsvImportId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("csv_import_id");

                    b.Property<string>("CsvImportId1")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("csv_import_id1");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Memo")
                        .HasColumnType("longtext")
                        .HasColumnName("memo");

                    b.Property<string>("Place")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("place");

                    b.Property<string>("RecurringTransactionId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("recurring_transaction_id");

                    b.Property<string>("RecurringTransactionId1")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("recurring_transaction_id1");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserId1")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id1");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("CsvImportId")
                        .HasDatabaseName("ix_transactions_csv_import_id");

                    b.HasIndex("CsvImportId1")
                        .HasDatabaseName("ix_transactions_csv_import_id1");

                    b.HasIndex("RecurringTransactionId")
                        .HasDatabaseName("ix_transactions_recurring_transaction_id");

                    b.HasIndex("RecurringTransactionId1")
                        .HasDatabaseName("ix_transactions_recurring_transaction_id1");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_transactions_user_id");

                    b.HasIndex("UserId1")
                        .HasDatabaseName("ix_transactions_user_id1");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("IsVerifield")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("is_verifield");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("login_id");

                    b.Property<string>("MailAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mail_address");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HouseholdBudget.Infrastructure.EFCore.EFEntities.CsvImports", b =>
                {
                    b.HasOne("Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_csv_imports_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HouseholdBudget.Infrastructure.EFCore.EFEntities.RecurringTransactions", b =>
                {
                    b.HasOne("Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_transactions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HouseholdBudget.Infrastructure.EFCore.EFEntities.Transactions", b =>
                {
                    b.HasOne("HouseholdBudget.Infrastructure.EFCore.EFEntities.CsvImports", null)
                        .WithMany()
                        .HasForeignKey("CsvImportId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transactions_csv_imports_csv_import_id");

                    b.HasOne("HouseholdBudget.Infrastructure.EFCore.EFEntities.CsvImports", "CsvImport")
                        .WithMany()
                        .HasForeignKey("CsvImportId1")
                        .HasConstraintName("fk_transactions_csv_imports_csv_import_id1");

                    b.HasOne("HouseholdBudget.Infrastructure.EFCore.EFEntities.RecurringTransactions", null)
                        .WithMany()
                        .HasForeignKey("RecurringTransactionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transactions_recurring_transactions_recurring_transaction_id");

                    b.HasOne("HouseholdBudget.Infrastructure.EFCore.EFEntities.RecurringTransactions", "RecurringTransaction")
                        .WithMany()
                        .HasForeignKey("RecurringTransactionId1")
                        .HasConstraintName("fk_transactions_recurring_transactions_recurring_transaction_id1");

                    b.HasOne("Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_users_user_id");

                    b.HasOne("Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_users_user_id1");

                    b.Navigation("CsvImport");

                    b.Navigation("RecurringTransaction");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
